package edu.mit.db.rstore;

import java.util.Hashtable;
import java.util.LinkedList;

public interface RDFBrowser{

	/**
	 * Schema generated by the SchemaGenerated dispalyed on the servlet
	 * 
	 */
	public void displaySchema(LinkedList<String> schemaStructure);
	
	/**
	 * Display the data from the RDF-Store
	 * 
	 */
	public void displayData(LinkedList<String> data);
	
	/**
	 * Run sql query from the user
	 * 
	 * @return
	 */
	public Hashtable runQuery(String query);
}
