package edu.mit.db.rstore;

import java.util.Hashtable;

public interface RDFBrowser{

	/**
	 * Schema generated by the SchemaGenerated dispalyed on the servlet
	 * 
	 */
	public void displaySchema();
	
	/**
	 * Display the data from the RDF-Store
	 * 
	 */
	public void displayData();
	
	/**
	 * Run sql query from the user
	 * 
	 * @return
	 */
	public Hashtable runQuery(String query);
}
